bmp2asm title.bmp > title.i
bmp2asm select.bmp > select.i
bmp2asm help1.bmp > help1.i
bmp2asm help2.bmp > help2.i
bmp2asm help3.bmp > help3.i
bmp2asm help4.bmp > help4.i
bmp2asm help5.bmp > help5.i
bmp2asm help6.bmp > help6.i
bmp2asm help7.bmp > help7.i
bmp2asm help8.bmp > help8.i
bmp2asm set_T1L.bmp > set_T1L.i
bmp2asm set_FREQ.bmp > set_FREQ.i